# Logistics Delivery Performance & Cost Analytics

## 1. Business Understanding

### Business Problem

The logistics business needs to understand delivery performance, delivery delays, logistics costs, warehouse performance, shipping mode performance, delivery partner performance, customer ratings, returns, and damages.

### Business Objectives

- Measure overall delivery performance
- Identify delayed deliveries
- Analyze route performance
- Analyze warehouse performance
- Analyze shipping mode performance
- Analyze delivery partner performance
- Analyze logistics costs
- Understand customer ratings
- Analyze return and damage rates

### Business Questions

1. What is the total number of orders?
2. How many orders were delivered?
3. How many orders were delayed?
4. What percentage of deliveries were on time?
5. What is the average delivery time?
6. Which routes experience higher delays?
7. Which warehouses have higher delays?
8. Which shipping modes have higher costs?
9. Which delivery partners handle the most shipments?
10. What is the total logistics cost?
11. What is the average customer rating?
12. What are the return and damage rates?

In [8]:
import os
import sys

print("Current working directory:")
print(os.getcwd())

print("\nFiles/folders here:")
print(os.listdir())

print("\nPython search paths:")
print(sys.path)

Current working directory:
C:\Users\lenova\Downloads\Logistic_delivery_analysis

Files/folders here:
['.ipynb_checkpoints', '.pytest_cache', '.venv', '.vscode', 'flow.bat', 'logistics_analysis.ipynb', 'logistics_delivery_analytics', 'run_dashboard.bat']

Python search paths:
['C:\\Users\\lenova\\Downloads', 'C:\\Users\\lenova\\AppData\\Local\\Programs\\Python\\Python312\\python312.zip', 'C:\\Users\\lenova\\AppData\\Local\\Programs\\Python\\Python312\\DLLs', 'C:\\Users\\lenova\\AppData\\Local\\Programs\\Python\\Python312\\Lib', 'C:\\Users\\lenova\\AppData\\Local\\Programs\\Python\\Python312', '', 'C:\\Users\\lenova\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages', 'C:\\Users\\lenova\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\win32', 'C:\\Users\\lenova\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\win32\\lib', 'C:\\Users\\lenova\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\Pythonwin']

In [10]:
import os
import sys

# Add the actual project folder to Python's search path
PROJECT_ROOT = os.path.join(
    os.getcwd(),
    "logistics_delivery_analytics"
)

if PROJECT_ROOT not in sys.path:
    sys.path.insert(0, PROJECT_ROOT)

print("Project root:", PROJECT_ROOT)
print("src folder exists:", os.path.exists(os.path.join(PROJECT_ROOT, "src")))

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from src.data_loader import load_data
from src.data_cleaner import clean_data

print("Libraries imported successfully!")

Project root: C:\Users\lenova\Downloads\Logistic_delivery_analysis\logistics_delivery_analytics
src folder exists: True
Libraries imported successfully!

In [33]:
from src.business_analysis import (
    calculate_total_orders,
    calculate_total_delivered,
    calculate_total_delayed,
    calculate_on_time_percentage,
    calculate_average_delivery_days,
    calculate_average_delay_days,
    calculate_total_shipping_cost,
    calculate_average_shipping_cost,
    calculate_total_fuel_cost,
    calculate_total_logistics_cost,
    calculate_average_logistics_cost,
    calculate_average_cost_per_km,
    calculate_average_customer_rating,
    calculate_return_rate,
    calculate_damage_rate
)

print("Business analysis functions imported successfully!")

Business analysis functions imported successfully!

In [14]:
raw_path = "logistics_delivery_analytics/data/raw/logistics_data.csv"

df = load_data(raw_path)

print("Raw data loaded successfully!")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Raw data loaded successfully!
Rows: 5000
Columns: 22

In [15]:
df.head()

,order_id,customer_id,order_date,warehouse,origin_city,destination_city,distance_km,product_category,quantity,weight_kg,...,shipping_cost,fuel_cost,warehouse_processing_hours,dispatch_date,expected_delivery_date,actual_delivery_date,delivery_status,customer_rating,damage_flag,return_flag
0,ORD101253,CUST12780,2025-03-12,Bengaluru,Bengaluru,Chennai,451.7,Home & Kitchen,7,5.51,...,2044.56,381.66,8.36,2025-03-14,2025-03-19,2025-03-24,Delayed,3.0,No,No
1,ORD102838,CUST11842,2025-12-02,Delhi,Delhi,Surat,592.8,Automotive,1,1.05,...,2582.70,385.02,10.33,2025-12-05,2025-12-12,2025-12-12,Delivered,4.0,No,No
2,ORD103457,CUST10940,2025-04-21,Pune,Pune,Nagpur,191.9,Clothing,3,9.09,...,817.23,185.83,8.88,2025-04-23,2025-04-28,2025-04-28,Delivered,5.0,No,No
3,ORD100061,CUST10263,2025-02-21,Pune,Pune,Coimbatore,376.4,Clothing,7,1.34,...,1713.22,386.35,10.18,2025-02-24,2025-03-02,2025-03-04,Delayed,3.0,No,No
4,ORD103947,CUST12467,2025-08-22,Mumbai,Mumbai,Delhi,895.3,Sports,5,3.95,...,3980.06,990.42,11.17,2025-08-24,2025-08-30,2025-08-30,Delivered,4.0,No,No

In [16]:
df.tail()

,order_id,customer_id,order_date,warehouse,origin_city,destination_city,distance_km,product_category,quantity,weight_kg,...,shipping_cost,fuel_cost,warehouse_processing_hours,dispatch_date,expected_delivery_date,actual_delivery_date,delivery_status,customer_rating,damage_flag,return_flag
4995,ORD100976,CUST10660,2025-10-17,Delhi,Delhi,Bengaluru,150.0,Clothing,5,10.55,...,793.26,182.51,10.59,2025-10-20,2025-10-25,2025-10-25,Delivered,4.0,No,No
4996,ORD101985,CUST11721,2025-07-05,Mumbai,Mumbai,Pune,625.2,Home & Kitchen,7,3.17,...,5781.16,663.26,12.09,2025-07-08,2025-07-11,2025-07-14,Delayed,4.0,No,No
4997,ORD101270,CUST11701,2025-07-23,Chennai,Chennai,Lucknow,409.2,Clothing,6,2.10,...,1899.21,465.21,4.70,2025-07-24,2025-07-30,2025-08-02,Delayed,4.0,Yes,No
4998,ORD104393,CUST10864,2025-03-08,Chennai,Chennai,Kolkata,158.0,Grocery,6,11.25,...,1016.99,94.64,6.91,2025-03-09,2025-03-14,2025-03-14,Delivered,4.0,No,No
4999,ORD101274,CUST10398,2025-07-03,Mumbai,Mumbai,Delhi,607.5,Home & Kitchen,4,7.85,...,2043.30,515.49,10.52,2025-07-07,2025-07-13,2025-07-13,Delivered,4.0,No,No

In [17]:
print("Data Types:")
print(df.dtypes)

Data Types:
order_id                       object
customer_id                    object
order_date                     object
warehouse                      object
origin_city                    object
destination_city               object
distance_km                   float64
product_category               object
quantity                        int64
weight_kg                     float64
shipping_mode                  object
delivery_partner               object
shipping_cost                 float64
fuel_cost                     float64
warehouse_processing_hours    float64
dispatch_date                  object
expected_delivery_date         object
actual_delivery_date           object
delivery_status                object
customer_rating               float64
damage_flag                    object
return_flag                    object
dtype: object

In [18]:
df.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
order_id,5000,4975,ORD101022,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
customer_id,5000,2328,CUST11656,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN
order_date,5000,365,2025-12-15,24,NaN,NaN,NaN,NaN,NaN,NaN,NaN
warehouse,5000,12,Hyderabad,1080,NaN,NaN,NaN,NaN,NaN,NaN,NaN
origin_city,5000,6,Hyderabad,1090,NaN,NaN,NaN,NaN,NaN,NaN,NaN
destination_city,4960,18,Indore,333,NaN,NaN,NaN,NaN,NaN,NaN,NaN
distance_km,5000.0,NaN,NaN,NaN,411.09862,260.537306,-25.0,221.775,354.35,541.8,1800.0
product_category,5000,16,Books,659,NaN,NaN,NaN,NaN,NaN,NaN,NaN
quantity,5000.0,NaN,NaN,NaN,3.967,2.009955,0.0,2.0,4.0,6.0,7.0
weight_kg,5000.0,NaN,NaN,NaN,5.528694,3.921885,0.2,2.7,4.64,7.4225,34.09
shipping_mode,5000,8,Road,2507,NaN,NaN,NaN,NaN,NaN,NaN,NaN
delivery_partner,5000,12,Ecom Express,852,NaN,NaN,NaN,NaN,NaN,NaN,NaN
shipping_cost,4950.0,NaN,NaN,NaN,2286.791669,1682.276034,-100.0,1141.0125,1808.2,2906.355,16275.33
fuel_cost,4950.0,NaN,NaN,NaN,373.230737,246.607318,20.0,194.93,319.115,497.0375,1755.71
warehouse_processing_hours,4941.0,NaN,NaN,NaN,8.391716,2.306332,2.0,6.81,8.38,10.02,15.65
dispatch_date,5000,367,2025-02-24,26,NaN,NaN,NaN,NaN,NaN,NaN,NaN
expected_delivery_date,5000,371,2025-12-03,32,NaN,NaN,NaN,NaN,NaN,NaN,NaN
actual_delivery_date,5000,374,2025-04-21,24,NaN,NaN,NaN,NaN,NaN,NaN,NaN
delivery_status,5000,2,Delivered,3801,NaN,NaN,NaN,NaN,NaN,NaN,NaN
customer_rating,4911.0,NaN,NaN,NaN,4.124822,0.71134,2.0,4.0,4.0,5.0,5.0
damage_flag,5000,2,No,4857,NaN,NaN,NaN,NaN,NaN,NaN,NaN
return_flag,5000,2,No,4783,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
print("Unique Values in Important Columns")

print("\nWarehouses:")
print(df["warehouse"].unique())

print("\nShipping Modes:")
print(df["shipping_mode"].unique())

print("\nDelivery Partners:")
print(df["delivery_partner"].unique())

print("\nDelivery Status:")
print(df["delivery_status"].unique())

Unique Values in Important Columns

Warehouses:
['Bengaluru' 'Delhi' 'Pune' 'Mumbai' 'Chennai' 'Hyderabad' 'pune'
 'bengaluru' 'hyderabad' 'mumbai' 'chennai' 'delhi']

Shipping Modes:
['Road' 'Rail' 'Air' 'Express' 'road' 'air' 'express' 'rail']

Delivery Partners:
['DTDC' 'Delhivery' 'Shadowfax' 'Blue Dart' 'XpressBees' 'Ecom Express'
 'ecom express' 'blue dart' 'xpressbees' 'shadowfax' 'delhivery' 'dtdc']

Delivery Status:
['Delayed' 'Delivered']

# 4. Basic Data Understanding

This section provides an initial understanding of the logistics dataset.
It examines the dataset structure, columns, data types, statistical
summary, and important categorical values.

In [20]:
cleaned_df = clean_data(df)

print("Data cleaning completed!")
print("Original rows:", df.shape[0])
print("Cleaned rows:", cleaned_df.shape[0])
print("Original columns:", df.shape[1])
print("Cleaned columns:", cleaned_df.shape[1])

Data cleaning completed!
Original rows: 5000
Cleaned rows: 4975
Original columns: 22
Cleaned columns: 27

In [21]:
cleaned_df.head()

,order_id,customer_id,order_date,warehouse,origin_city,destination_city,distance_km,product_category,quantity,weight_kg,...,actual_delivery_date,delivery_status,customer_rating,damage_flag,return_flag,delivery_days,delay_days,cost_per_km,total_logistics_cost,on_time_flag
0,ORD101253,CUST12780,2025-03-12,Bengaluru,Bengaluru,Chennai,451.7,Home & Kitchen,7.0,5.51,...,2025-03-24,Delayed,3.0,0,0,10,5,4.526367,2426.22,0
1,ORD102838,CUST11842,2025-12-02,Delhi,Delhi,Surat,592.8,Automotive,1.0,1.05,...,2025-12-12,Delivered,4.0,0,0,7,0,4.356781,2967.72,1
2,ORD103457,CUST10940,2025-04-21,Pune,Pune,Nagpur,191.9,Clothing,3.0,9.09,...,2025-04-28,Delivered,5.0,0,0,5,0,4.258624,1003.06,1
3,ORD100061,CUST10263,2025-02-21,Pune,Pune,Coimbatore,376.4,Clothing,7.0,1.34,...,2025-03-04,Delayed,3.0,0,0,8,2,4.551594,2099.57,0
4,ORD103947,CUST12467,2025-08-22,Mumbai,Mumbai,Delhi,895.3,Sports,5.0,3.95,...,2025-08-30,Delivered,4.0,0,0,6,0,4.445504,4970.48,1

In [22]:
print("Missing values after cleaning:")

print(
    cleaned_df.isnull().sum()
)

Missing values after cleaning:
order_id                      0
customer_id                   0
order_date                    0
warehouse                     0
origin_city                   0
destination_city              0
distance_km                   0
product_category              0
quantity                      0
weight_kg                     0
shipping_mode                 0
delivery_partner              0
shipping_cost                 0
fuel_cost                     0
warehouse_processing_hours    0
dispatch_date                 0
expected_delivery_date        0
actual_delivery_date          0
delivery_status               0
customer_rating               0
damage_flag                   0
return_flag                   0
delivery_days                 0
delay_days                    0
cost_per_km                   0
total_logistics_cost          0
on_time_flag                  0
dtype: int64

In [23]:
print(
    "Duplicate rows after cleaning:",
    cleaned_df.duplicated().sum()
)

Duplicate rows after cleaning: 0

# 7. Derived Columns

In [24]:
derived_columns = [
    "delivery_days",
    "delay_days",
    "cost_per_km",
    "total_logistics_cost",
    "on_time_flag"
]

cleaned_df[derived_columns].head()

   delivery_days  delay_days  cost_per_km  total_logistics_cost  on_time_flag
0             10           5     4.526367               2426.22             0
1              7           0     4.356781               2967.72             1
2              5           0     4.258624               1003.06             1
3              8           2     4.551594               2099.57             0
4              6           0     4.445504               4970.48             1

In [25]:
cleaned_df[
    [
        "dispatch_date",
        "actual_delivery_date",
        "expected_delivery_date",
        "delivery_days",
        "delay_days",
        "cost_per_km",
        "total_logistics_cost",
        "on_time_flag"
    ]
].head(10)

,dispatch_date,actual_delivery_date,expected_delivery_date,delivery_days,delay_days,cost_per_km,total_logistics_cost,on_time_flag
0,2025-03-14,2025-03-24,2025-03-19,10,5,4.526367,2426.22,0
1,2025-12-05,2025-12-12,2025-12-12,7,0,4.356781,2967.72,1
2,2025-04-23,2025-04-28,2025-04-28,5,0,4.258624,1003.06,1
3,2025-02-24,2025-03-04,2025-03-02,8,2,4.551594,2099.57,0
4,2025-08-24,2025-08-30,2025-08-30,6,0,4.445504,4970.48,1
5,2025-03-13,2025-03-16,2025-03-16,3,0,8.954002,5049.15,1
6,2025-03-06,2025-03-13,2025-03-13,7,0,4.575512,4767.06,1
7,2025-11-12,2025-11-18,2025-11-18,6,0,4.428470,3060.44,1
8,2025-02-19,2025-02-22,2025-02-22,3,0,9.405936,4859.05,1
9,2025-09-21,2025-10-03,2025-09-28,12,5,3.350032,1333.49,0

# 8. EDA

In [26]:
cleaned_df.describe().T

,count,mean,min,25%,50%,75%,max,std
order_date,4975,2025-06-29 15:27:40.703517696,2025-01-01 00:00:00,2025-04-01 12:00:00,2025-06-29 00:00:00,2025-09-28 00:00:00,2025-12-31 00:00:00,NaN
distance_km,4975.0,411.187276,28.8,221.9,354.2,541.8,1800.0,260.196345
quantity,4975.0,3.97206,0.0,2.0,4.0,6.0,7.0,2.009383
weight_kg,4975.0,5.526474,0.2,2.7,4.63,7.42,34.09,3.919012
shipping_cost,4975.0,2281.061371,121.54,1147.115,1808.2,2891.865,16275.33,1671.922649
fuel_cost,4975.0,372.459769,20.0,195.645,319.115,493.655,1755.71,245.263321
warehouse_processing_hours,4975.0,8.39003,2.0,6.83,8.38,10.0,15.65,2.293709
dispatch_date,4975,2025-07-01 21:40:29.185929472,2025-01-02 00:00:00,2025-04-04 00:00:00,2025-07-02 00:00:00,2025-09-30 00:00:00,2026-01-03 00:00:00,NaN
expected_delivery_date,4975,2025-07-06 19:47:18.753768704,2025-01-05 00:00:00,2025-04-08 00:00:00,2025-07-07 00:00:00,2025-10-05 00:00:00,2026-01-10 00:00:00,NaN
actual_delivery_date,4975,2025-07-07 12:41:14.773869056,2025-01-05 00:00:00,2025-04-09 00:00:00,2025-07-07 00:00:00,2025-10-05 00:00:00,2026-01-14 00:00:00,NaN
customer_rating,4975.0,4.122412,2.0,4.0,4.0,5.0,5.0,0.705606
damage_flag,4975.0,0.028543,0.0,0.0,0.0,0.0,1.0,0.166534
return_flag,4975.0,0.043618,0.0,0.0,0.0,0.0,1.0,0.204264
delivery_days,4975.0,5.625528,1.0,4.0,5.0,7.0,15.0,2.252611
delay_days,4975.0,0.704121,0.0,0.0,0.0,0.0,7.0,1.506884
cost_per_km,4975.0,5.772941,1.190859,4.285732,4.697503,7.358957,37.359504,2.273049
total_logistics_cost,4975.0,2653.52114,141.54,1371.565,2158.34,3393.13,17602.9,1862.425383
on_time_flag,4975.0,0.761005,0.0,1.0,1.0,1.0,1.0,0.426513

In [27]:
cleaned_df["delivery_status"].value_counts()

delivery_status
Delivered    3786
Delayed      1189
Name: count, dtype: int64

In [28]:
cleaned_df["shipping_mode"].value_counts()

shipping_mode
Road       2499
Rail        925
Air         904
Express     607
road         22
air           7
rail          6
express       5
Name: count, dtype: int64

In [29]:
cleaned_df["warehouse"].value_counts()

warehouse
Hyderabad    1078
Bengaluru     882
Pune          782
Chennai       758
Mumbai        734
Delhi         701
pune            9
hyderabad       9
chennai         7
mumbai          6
bengaluru       5
delhi           4
Name: count, dtype: int64

In [30]:
cleaned_df["delivery_partner"].value_counts()

delivery_partner
Ecom Express    847
Shadowfax       835
XpressBees      835
Delhivery       826
DTDC            803
Blue Dart       790
blue dart         9
xpressbees        9
ecom express      6
shadowfax         6
dtdc              6
delhivery         3
Name: count, dtype: int64

# 9. KPI Analysis

In [34]:
print("Total Orders:", calculate_total_orders(cleaned_df))

print("Total Delivered:", calculate_total_delivered(cleaned_df))

print("Total Delayed:", calculate_total_delayed(cleaned_df))

print(
    "On-Time Delivery Percentage:",
    round(calculate_on_time_percentage(cleaned_df), 2),
    "%"
)

print(
    "Average Delivery Days:",
    round(calculate_average_delivery_days(cleaned_df), 2)
)

print(
    "Average Delay Days:",
    round(calculate_average_delay_days(cleaned_df), 2)
)

print(
    "Total Shipping Cost:",
    round(calculate_total_shipping_cost(cleaned_df), 2)
)

print(
    "Average Shipping Cost:",
    round(calculate_average_shipping_cost(cleaned_df), 2)
)

print(
    "Total Fuel Cost:",
    round(calculate_total_fuel_cost(cleaned_df), 2)
)

print(
    "Total Logistics Cost:",
    round(calculate_total_logistics_cost(cleaned_df), 2)
)

print(
    "Average Logistics Cost:",
    round(calculate_average_logistics_cost(cleaned_df), 2)
)

print(
    "Average Cost per KM:",
    round(calculate_average_cost_per_km(cleaned_df), 2)
)

print(
    "Average Customer Rating:",
    round(calculate_average_customer_rating(cleaned_df), 2)
)

print(
    "Return Rate:",
    round(calculate_return_rate(cleaned_df), 2),
    "%"
)

print(
    "Damage Rate:",
    round(calculate_damage_rate(cleaned_df), 2),
    "%"
)

Total Orders: 4975
Total Delivered: 3786
Total Delayed: 1189
On-Time Delivery Percentage: 76.1 %
Average Delivery Days: 5.63
Average Delay Days: 2.95
Total Shipping Cost: 11348280.32
Average Shipping Cost: 2281.06
Total Fuel Cost: 1852987.35
Total Logistics Cost: 13201267.67
Average Logistics Cost: 2653.52
Average Cost per KM: 5.77
Average Customer Rating: 4.12
Return Rate: 4.36 %
Damage Rate: 2.85 %

# 10. Business Analysis

In [36]:
route_performance = analyze_route_performance(cleaned_df)

route_performance.head(10)

NameError: name 'analyze_route_performance' is not defined